kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azurenetappfiles
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurenetappfiles