apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-anf-elastic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: netapp-anf-perf-standard